# Analog Adventures Test / Tin Roof Holdings, LLC
# This is the canonical configuration for local development and test deployment.

client_id = "8158f984f0ec6fed1e5f85b44a588777"
name = "analog-adv-brand-portal"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
scopes = "read_companies,read_customers,read_orders,read_products,write_products,read_metaobjects,write_metaobjects,read_metaobject_definitions,write_metaobject_definitions,read_files,write_files,read_draft_orders,write_draft_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
