api_version = "2026-07"

[[extensions]]
name = "Brand Portal"
handle = "brand-portal"
type = "ui_extension"
uid = "f6f2b9ec-2581-6aa3-b9b0-241fdf4c4314b30a368a"

[[extensions.targeting]]
module = "./src/PortalPage.jsx"
target = "customer-account.page.render"

[extensions.capabilities]
api_access = true
network_access = true

[extensions.settings]

  [[extensions.settings.fields]]
  key = "portal_api_url"
  type = "single_line_text_field"
  name = "Portal API URL"
  description = "Full app URL ending in /public/portal"
